import type { Metadata } from "next";
import { Rubik, Questrial } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});

const questrial = Questrial({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-questrial",
});

export const metadata: Metadata = {
  title: "Fresh Harvest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rubik.variable} ${questrial.variable}`}>
      <body className={"font-rubik antialiased"} 
      data-new-gr-c-s-check-loaded="14.1237.0" data-gr-ext-installed=""
      >
        <NavBar></NavBar>
        {children}
        <Footer />
      </body>
    </html>
  );
}
